# Generated by Django 5.2.17 on 2026-09-19 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(blank=True, max_length=150)),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('travel_date', models.DateField(blank=True, null=True)),
                ('passengers', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('tempo', 'Tempo Traveller')], max_length=50)),
                ('phone_number', models.CharField(max_length=15)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('hero', 'Hero Section - Quick Enquiry'), ('contact', 'Contact Page Form')], default='hero', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Customer Enquiry',
                'verbose_name_plural': 'Customer Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_label', models.CharField(default='MADURAI · TAMIL NADU · SOUTH INDIA', max_length=100)),
                ('heading_main', models.CharField(default='Explore South India With', max_length=200)),
                ('heading_highlight', models.CharField(default='Comfort & Confidence', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('button1_text', models.CharField(default='Book Your Ride', max_length=50)),
                ('button1_link', models.CharField(default='#quick-enquiry', max_length=300)),
                ('button2_text', models.CharField(default='Explore Packages', max_length=50)),
                ('button2_link', models.CharField(default='#packages', max_length=300)),
                ('background_image', models.ImageField(upload_to='hero/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage Hero',
                'verbose_name_plural': 'Homepage Hero',
            },
        ),
    ]
