# Generated by Django 5.2.17 on 2026-09-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='trust_badge_1',
            field=models.CharField(blank=True, default='Local expertise', max_length=60),
        ),
        migrations.AddField(
            model_name='herosection',
            name='trust_badge_2',
            field=models.CharField(blank=True, default='Flexible itineraries', max_length=60),
        ),
        migrations.AddField(
            model_name='herosection',
            name='trust_badge_3',
            field=models.CharField(blank=True, default='Direct support', max_length=60),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('mini', 'Mini / Hatchback'), ('sedan', 'Sedan'), ('suv', 'SUV'), ('innova', 'Innova'), ('innova_crysta', 'Innova Crysta'), ('tempo', 'Tempo Traveller')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, help_text='e.g. TOURS & TRAVELS', max_length=150),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Digits only with country code, e.g. 919876543210', max_length=20),
        ),
    ]
