# Generated by Django 5.2.17 on 2026-09-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0003_herosection_trust_badge_1_herosection_trust_badge_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('heart', 'Heart'), ('map', 'Map'), ('headphones', 'Headphones'), ('award', 'Award / Medal'), ('car', 'Car')], default='heart', max_length=20)),
                ('label_top', models.CharField(help_text="Small text above, e.g. 'Serving'", max_length=60)),
                ('label_bottom', models.CharField(help_text="Bold text below, e.g. 'Travellers'", max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Trust Stat',
                'verbose_name_plural': 'Trust Stats (Serving Travellers row)',
                'ordering': ['order'],
            },
        ),
    ]
