# Generated by Django 5.2.17 on 2026-09-19 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0004_truststat'),
    ]

    operations = [
        migrations.CreateModel(
            name='FleetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='RIDE YOUR WAY', max_length=100)),
                ('heading', models.CharField(default='Our Comfortable Fleet', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Choose a vehicle that fits your group, luggage and journey.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fleet Section Heading',
                'verbose_name_plural': 'Fleet Section Heading',
            },
        ),
        migrations.CreateModel(
            name='FleetVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='fleet/')),
                ('name', models.CharField(help_text='e.g. Sedan, Innova Crysta', max_length=100)),
                ('passengers', models.CharField(help_text="e.g. '4 passengers' or '6-7 passengers'", max_length=50)),
                ('bags', models.CharField(help_text="e.g. '3 bags' or 'Group luggage'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fleet Vehicle',
                'verbose_name_plural': 'Fleet Vehicles',
                'ordering': ['order'],
            },
        ),
    ]
