# Generated by Django 5.2.17 on 2026-09-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0005_fleetsection_fleetvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='CURATED JOURNEYS', max_length=100)),
                ('heading', models.CharField(default='Popular Madurai Tour Packages', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Discover carefully planned journeys across the most beautiful destinations in South India.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Packages Section Heading',
                'verbose_name_plural': 'Packages Section Heading',
            },
        ),
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('duration', models.CharField(default='2 Days', help_text="e.g. '2 Days', '3 Days'", max_length=30)),
                ('location_tag', models.CharField(help_text="e.g. 'MADURAI · RAMESHWARAM'", max_length=150)),
                ('title', models.CharField(help_text="e.g. 'Madurai – Rameshwaram – 2 Days'", max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tour Package',
                'verbose_name_plural': 'Tour Packages',
                'ordering': ['order'],
            },
        ),
    ]
