# Generated by Django 5.2.17 on 2026-09-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0006_packagessection_tourpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('car', 'Car'), ('route', 'Route'), ('plane', 'Plane'), ('map_pin', 'Map Pin'), ('sparkles', 'Sparkles'), ('users', 'Users')], default='car', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('title', models.CharField(help_text="e.g. 'Local Cab Service'", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServicesSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='WAYS TO TRAVEL', max_length=100)),
                ('heading', models.CharField(default='Travel Services Designed Around You', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='From a quick city ride to a multi-day South India journey, every trip is thoughtfully arranged.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Services Section Heading',
                'verbose_name_plural': 'Services Section Heading',
            },
        ),
    ]
