# Generated by Django 5.2.17 on 2026-09-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0007_service_servicessection'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhyUsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('award', 'Award'), ('car', 'Car'), ('ticket', 'Ticket'), ('map', 'Map'), ('headphones', 'Headphones'), ('shield', 'Shield Check'), ('sparkles', 'Sparkles'), ('navigation', 'Navigation')], default='award', max_length=20)),
                ('title', models.CharField(help_text="e.g. 'Experienced Drivers'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Us Item',
                'verbose_name_plural': 'Why Us Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WhyUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='THE VISMI DIFFERENCE', max_length=100)),
                ('heading', models.CharField(default='Why Travel With Us?', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Thoughtful planning, reliable support and genuine local knowledge for every mile.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Why Us Section Heading',
                'verbose_name_plural': 'Why Us Section Heading',
            },
        ),
    ]
