# Generated by Django 5.2.17 on 2026-09-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0008_whyusitem_whyussection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='destinations/')),
                ('name', models.CharField(help_text="e.g. 'Madurai', 'Rameshwaram'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DestinationsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='GO FURTHER', max_length=100)),
                ('heading', models.CharField(default='Explore Popular Destinations', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='From sacred temple towns to misty hill stations and sunlit coastlines.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Destinations Section Heading',
                'verbose_name_plural': 'Destinations Section Heading',
            },
        ),
    ]
