# Generated by Django 5.2.17 on 2026-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0009_destination_destinationssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('map_pin', 'Map Pin'), ('car', 'Car'), ('ticket', 'Ticket'), ('palm', 'Palm Tree')], default='map_pin', max_length=20)),
                ('title', models.CharField(help_text="e.g. 'Choose Your Destination'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Booking Step',
                'verbose_name_plural': 'Booking Steps',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='StepsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='SIMPLE BOOKING', max_length=100)),
                ('heading', models.CharField(default='Your Journey, In Four Easy Steps', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Steps Section Heading',
                'verbose_name_plural': 'Steps Section Heading',
            },
        ),
    ]
