# Generated by Django 5.2.17 on 2026-09-20 06:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0010_step_stepssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='ABOUT US', max_length=100)),
                ('heading', models.CharField(default='Your Trusted Travel Partner in Madurai', max_length=200)),
                ('paragraph_1', models.TextField(blank=True, default='Madurai Vismi Cabs is a Madurai-based travel service helping guests experience South India with greater comfort and confidence. We arrange local cabs, airport transfers, outstation travel and customized tour packages with a customer-first approach.')),
                ('paragraph_2', models.TextField(blank=True, default='Our local travel expertise, experienced drivers and comfortable vehicle options make every journey feel simpler—from temple visits to family holidays and multi-day circuits.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('badge_title', models.CharField(default='Madurai', max_length=60)),
                ('badge_subtitle', models.CharField(default='Your South India gateway', max_length=100)),
                ('button_text', models.CharField(default='Plan Your Trip', max_length=50)),
                ('button_link', models.CharField(default='#quick-enquiry', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Section',
            },
        ),
        migrations.CreateModel(
            name='AboutChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text="e.g. 'Local route knowledge'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='landing_app.aboutsection')),
            ],
            options={
                'verbose_name': 'About Checklist Item',
                'verbose_name_plural': 'About Checklist Items',
                'ordering': ['order'],
            },
        ),
    ]
