# Generated by Django 5.2.17 on 2026-09-20 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0011_aboutsection_aboutchecklistitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Arun Kumar'", max_length=100)),
                ('location', models.CharField(help_text="e.g. 'Madurai & Rameshwaram'", max_length=150)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Stars'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5)),
                ('quote', models.TextField(help_text='The review text')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ReviewsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='GUEST STORIES', max_length=100)),
                ('heading', models.CharField(default='What Our Customers Say', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Sample reviews shown for layout preview.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Reviews Section Heading',
                'verbose_name_plural': 'Reviews Section Heading',
            },
        ),
    ]
