# Generated by Django 5.2.17 on 2026-09-20 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0012_review_reviewssection'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/')),
                ('caption', models.CharField(help_text="e.g. 'Our Fleet', 'Kodaikanal'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Image',
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='ON THE ROAD', max_length=100)),
                ('heading', models.CharField(default='Travel Moments', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='A glimpse of the places, roads and experiences waiting across South India.', max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Gallery Section Heading',
                'verbose_name_plural': 'Gallery Section Heading',
            },
        ),
    ]
