# Generated by Django 5.2.17 on 2026-09-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0013_galleryimage_gallerysection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Item',
                'verbose_name_plural': 'FAQ Items',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='GOOD TO KNOW', max_length=100)),
                ('heading', models.CharField(default='Frequently Asked Questions', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='Need help planning? Speak directly with our travel team.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ Section Heading',
                'verbose_name_plural': 'FAQ Section Heading',
            },
        ),
    ]
