# Generated by Django 5.2.17 on 2026-09-20 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0014_faqitem_faqsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='START YOUR JOURNEY', max_length=100)),
                ('heading', models.CharField(default='Plan Your Journey With Us', max_length=150)),
                ('subtitle', models.CharField(blank=True, default="Tell us where you want to go. We'll help shape the right route, vehicle and travel plan.", max_length=250)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Contact Section Heading',
                'verbose_name_plural': 'Contact Section Heading',
            },
        ),
    ]
