# Generated by Django 5.2.17 on 2026-09-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0015_contactsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtaSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='THE ROAD IS WAITING', max_length=100)),
                ('heading', models.CharField(default='Ready to Explore South India?', max_length=150)),
                ('subtitle', models.CharField(blank=True, default='From temple trails to hill stations, let us make your journey comfortable and memorable.', max_length=250)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='cta/')),
                ('button1_text', models.CharField(default='Book Your Cab', max_length=50)),
                ('button2_text', models.CharField(default='Chat on WhatsApp', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Final CTA Section',
                'verbose_name_plural': 'Final CTA Section',
            },
        ),
    ]
