# Generated by Django 5.2.17 on 2026-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0016_ctasection'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column', models.CharField(choices=[('quick_links', 'Quick Links'), ('services', 'Services')], default='quick_links', max_length=20)),
                ('label', models.CharField(help_text="e.g. 'Home', 'Local Cab'", max_length=60)),
                ('url', models.CharField(help_text="Anchor to a section on this page, e.g. '#about', '#services', '#contact'", max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Link',
                'verbose_name_plural': 'Footer Links',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='Comfortable cab services and thoughtfully customized South India journeys from Madurai.')),
                ('tagline_note', models.CharField(blank=True, default='Journeys made personal in Madurai.', max_length=150)),
                ('copyright_text', models.CharField(default='© 2026 Madurai Vismi Cabs. All rights reserved.', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Section',
                'verbose_name_plural': 'Footer Section',
            },
        ),
        migrations.CreateModel(
            name='FooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X')], default='facebook', max_length=20)),
                ('url', models.URLField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Footer Social Link',
                'verbose_name_plural': 'Footer Social Links',
                'ordering': ['order'],
            },
        ),
    ]
