# Generated by Django 5.2.17 on 2026-09-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0017_footerlink_footersection_footersociallink'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='highlights',
            field=models.TextField(blank=True, help_text='One highlight per line, e.g.\n2 Days / 1 Night\nMadurai Sightseeing\nTemple & Heritage Attractions'),
        ),
    ]
