# Generated by Django 5.2.17 on 2026-09-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0018_tourpackage_highlights'),
    ]

    operations = [
        migrations.AddField(
            model_name='whyusitem',
            name='description',
            field=models.TextField(blank=True, help_text="e.g. 'Professional drivers focused on a smooth and comfortable travel experience.'"),
        ),
    ]
