# Generated by Django 5.2.17 on 2026-09-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_app', '0019_whyusitem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='description',
            field=models.TextField(blank=True, help_text="e.g. 'Share your destination, date, and travel requirements.'"),
        ),
    ]
